### ISSUE TITLE
is this based on the group samplebot?

### ISSUE THREAD

**Issue by codesimba** [virtualdom/alfred#9]
I was unable to get this loaded up and running, and there's not much of a guide.

**Comment by virtualdom** [comment]
Thanks for the heads up. Originally I just spun up Alfred for my friends, so I didn't plan on other people actually wanting to experiment with him.

I updated the `README.md` to be a bit more informative and I added an empty credentials file that you'll be responsible for filling out depending on your group/bot IDs.

Let me know if anything needs additional smoothing out 👍
